//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercoplano.Simplex.Server.MvcUI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interesse
    {
        public int Id { get; set; }
        public string Interesse1 { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string url { get; set; }
        public string urlanterior { get; set; }
    }
}
