//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercoplano.Simplex.Server.MvcUI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.Translation = new HashSet<Translation>();
        }
    
        public short LanguageId { get; set; }
        public string LanguageCode { get; set; }
        public string LanguageName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ObjectTypeId { get; set; }
        public string StatusId { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<int> TranslationId { get; set; }
    
        public virtual ICollection<Translation> Translation { get; set; }
    }
}
