//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercoplano.Simplex.Server.MvcUI.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SimplexEntities : DbContext
    {
        public SimplexEntities()
            : base("name=SimplexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Translation> Translation { get; set; }
        public virtual DbSet<TranslationDate> TranslationDate { get; set; }
        public virtual DbSet<Interesse> Interesse { get; set; }
    
        public virtual ObjectResult<LanguageSelectResult> LanguageSelect(Nullable<short> iN_LanguageId)
        {
            var iN_LanguageIdParameter = iN_LanguageId.HasValue ?
                new ObjectParameter("IN_LanguageId", iN_LanguageId) :
                new ObjectParameter("IN_LanguageId", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LanguageSelectResult>("LanguageSelect", iN_LanguageIdParameter);
        }
    
        public virtual int TranslationAjust(string iN_LabelName)
        {
            var iN_LabelNameParameter = iN_LabelName != null ?
                new ObjectParameter("IN_LabelName", iN_LabelName) :
                new ObjectParameter("IN_LabelName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TranslationAjust", iN_LabelNameParameter);
        }
    
        public virtual ObjectResult<TranslationSelectResult> TranslationSelect(Nullable<int> iN_TranslationId)
        {
            var iN_TranslationIdParameter = iN_TranslationId.HasValue ?
                new ObjectParameter("IN_TranslationId", iN_TranslationId) :
                new ObjectParameter("IN_TranslationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TranslationSelectResult>("TranslationSelect", iN_TranslationIdParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> TranslationDateSelect()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("TranslationDateSelect");
        }
    
        public virtual int InteresseInsert(string iN_Interesse, string iN_ur, string iN_urlanterior)
        {
            var iN_InteresseParameter = iN_Interesse != null ?
                new ObjectParameter("IN_Interesse", iN_Interesse) :
                new ObjectParameter("IN_Interesse", typeof(string));
    
            var iN_urParameter = iN_ur != null ?
                new ObjectParameter("IN_ur", iN_ur) :
                new ObjectParameter("IN_ur", typeof(string));
    
            var iN_urlanteriorParameter = iN_urlanterior != null ?
                new ObjectParameter("IN_urlanterior", iN_urlanterior) :
                new ObjectParameter("IN_urlanterior", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InteresseInsert", iN_InteresseParameter, iN_urParameter, iN_urlanteriorParameter);
        }
    
        public virtual ObjectResult<InteresseSelectResult> InteresseSelect()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InteresseSelectResult>("InteresseSelect");
        }
    }
}
