//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercoplano.Simplex.Server.MvcUI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public int TranslationId { get; set; }
        public short LanguageId { get; set; }
        public string LabelName { get; set; }
        public Nullable<short> LengthNumber { get; set; }
        public string DescriptionName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ObjectTypeId { get; set; }
        public string StatusId { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
